export const adviseColumns = [
  { key: 'rowId', value: '行号' },
  { key: 'subproductname4excel', value: '子产品名称' },
  { key: 'modulename4excel', value: '模块名称' },
  { key: 'name4excel', value: '建议名称' },
  { key: 'expect_releasetime4excel', value: '期望上线时间' },
  { key: 'description4excel', value: '建议描述' },
  { key: 'level4excel', value: '重要性' },
  { key: 'responseemail4excel', value: '建议负责人' },
  { key: 'submitemail4excel', value: '建议报告人' },
  { key: 'jirakey4excel', value: 'JIRA单子' },
  { key: 'state4excel', value: '状态' },
  { key: 'message', value: '原因' },
];

export const requirementColumns = [
  { key: 'rowId', value: '行号' },
  { key: 'subproductname4excel', value: '子产品名称' },
  { key: 'modulename4excel', value: '模块名称' },
  { key: 'name4excel', value: '需求名称' },
  { key: 'expect_releasetime4excel', value: '计划上线时间' },
  { key: 'description4excel', value: '需求描述' },
  { key: 'level4excel', value: '优先级' },
  { key: 'responseemail4excel', value: '需求负责人' },
  { key: 'submitemail4excel', value: '需求报告人' },
  { key: 'requireemail4excel', value: '需求验证人' },
  { key: 'jirakey4excel', value: 'JIRA单子' },
  { key: 'state4excel', value: '状态' },
  { key: 'message', value: '原因' },
];

export const taskColumns = [
  { key: 'rowId', value: '行号' },
  { key: 'subproductname4excel', value: '子产品名称' },
  { key: 'modulename4excel', value: '模块名称' },
  { key: 'name4excel', value: '任务名称' },
  { key: 'expect_releasetime4excel', value: '到期日' },
  { key: 'description4excel', value: '任务描述' },
  { key: 'level4excel', value: '优先级' },
  { key: 'estimate_cost4excel', value: '预估工作量' },
  { key: 'responseemail4excel', value: '任务负责人' },
  { key: 'submitemail4excel', value: '任务报告人' },
  { key: 'requireemail4excel', value: '任务验证人' },
  { key: 'jirakey4excel', value: 'JIRA单子' },
  { key: 'state4excel', value: '状态' },
  { key: 'message', value: '原因' },
];

export const bugColumns = [
  { key: 'rowId', value: '行号' },
  { key: 'subproductname4excel', value: '子产品名称' },
  { key: 'modulename4excel', value: '模块名称' },
  { key: 'name4excel', value: '缺陷名称' },
  { key: 'level4excel', value: '重要性' },
  { key: 'onlinebug4excel', value: '缺陷是否线上BUG' },
  { key: 'bugtype4excel', value: '缺陷BUG分类' },
  { key: 'description4excel', value: '缺陷描述' },
  { key: 'estimate_cost4excel', value: '预估工作量' },
  { key: 'expect_releasetime4excel', value: '到期日' },
  { key: 'responseemail4excel', value: '缺陷负责人' },
  { key: 'submitemail4excel', value: '缺陷报告人' },
  { key: 'requireemail4excel', value: '缺陷验证人' },
  { key: 'findversion4excel', value: '缺陷发现版本' },
  { key: 'fixversion4excel', value: '缺陷解决版本' },
  { key: 'jirakey4excel', value: 'JIRA单子' },
  { key: 'state4excel', value: '状态' },
  { key: 'message', value: '原因' },
];

export const objectiveColumns = [
  { key: 'rowId', value: '行号' },
  { key: 'subproductname4excel', value: '子产品名称' },
  { key: 'name4excel', value: '目标名称' },
  { key: 'expect_releasetime4excel', value: '到期日' },
  { key: 'level4excel', value: '优先级' },
  { key: 'type4excel', value: '目标类型' },
  { key: 'description4excel', value: '目标验收标准' },
  { key: 'remark4excel', value: '目标描述' },
  { key: 'responseemail4excel', value: '目标负责人' },
  { key: 'submitemail4excel', value: '目标报告人' },
  { key: 'requireemail4excel', value: '目标验证人' },
  { key: 'jirakey4excel', value: 'JIRA单子' },
  { key: 'state4excel', value: '状态' },
  { key: 'message', value: '原因' },
];

export const ticketColumns = [
  { key: 'rowId', value: '行号' },
  { key: 'subproductname4excel', value: '子产品名称' },
  { key: 'modulename4excel', value: '模块名称' },
  { key: 'name4excel', value: '工单名称' },
  { key: 'expect_releasetime4excel', value: '期望上线时间' },
  { key: 'description4excel', value: '工单描述' },
  { key: 'level4excel', value: '重要性' },
  { key: 'responseemail4excel', value: '工单负责人' },
  { key: 'submitemail4excel', value: '工单报告人' },
  { key: 'jirakey4excel', value: 'JIRA单子' },
  { key: 'state4excel', value: '状态' },
  { key: 'message', value: '原因' },
];
