export const data = [{
  projectId: '100',
  id: 'Objective-586',
  issueKey: "Objective-586",
  parentIssueKey: 'Objective-hidden0',
  issueRole: 1,
  issueType: 5,
  level: 3,
  name: "一级部门目标1",
  responseUser: { id: 122, name: "牛盼盼", email: "wb.niupanpan@mesg.corp.netease.com", department: "" },
  state: 1,
  column: 1,
  dueDate: '2020-10-10',
  keyResult: [{
    id: 1,
    name: '我是关键结果1'
  }, {
    id: 2,
    name: '我是关键结果2'
  }, {
    id: 3,
    name: '我是关键结果3'
  }],
  department: ['杭州研究院', '技术工程事业部', '项目管理与效能中心', '工程效能组'],
}, {
  bugCount: 0,
  dwManpower: {},
  id: 'Objective-4',
  issueKey: "Objective-4",
  parentIssueKey: 'Objective-586',
  issueRole: 1,
  issueType: 5,
  level: 3,
  name: "二级部门目标1",
  requirementCount: 5,
  responseUser: { id: 122, name: "牛盼盼", email: "wb.niupanpan@mesg.corp.netease.com", department: "" },
  state: 1,
  taskCount: 1,
  column: 2,
  dueDate: '2020-10-10',
  keyResult: [],
  department: ['杭州研究院', '技术工程事业部', '项目管理与效能中心', '工程效能组'],
}, {
  bugCount: 0,
  dwManpower: {},
  id: 'Objective-3',
  issueKey: "Objective-3",
  parentIssueKey: 'Objective-586',
  issueRole: 1,
  issueType: 5,
  level: 3,
  name: "二级部门目标2",
  requirementCount: 5,
  responseUser: { id: 122, name: "牛盼盼", email: "wb.niupanpan@mesg.corp.netease.com", department: "" },
  state: 1,
  taskCount: 1,
  column: 2,
  dueDate: '2020-10-10',
  keyResult: [],
  department: ['杭州研究院', '技术工程事业部', '项目管理与效能中心', '工程效能组'],
}, {
  bugCount: 0,
  dwManpower: {},
  id: 'Objective-31',
  issueKey: "Objective-31",
  parentIssueKey: 'Objective-586',
  issueRole: 1,
  issueType: 5,
  level: 3,
  name: "二级部门目标12",
  requirementCount: 5,
  responseUser: { id: 122, name: "牛盼盼", email: "wb.niupanpan@mesg.corp.netease.com", department: "" },
  state: 1,
  taskCount: 1,
  column: 2,
  dueDate: '2020-10-10',
  keyResult: [],
  department: ['杭州研究院', '技术工程事业部', '项目管理与效能中心', '工程效能组'],
}, {
  bugCount: 0,
  dwManpower: {},
  id: 'Objective-7',
  issueKey: "Objective-7",
  parentIssueKey: 'Objective-3',
  issueRole: 1,
  issueType: 5,
  level: 3,
  name: "三级部门目标7",
  requirementCount: 5,
  responseUser: { id: 122, name: "牛盼盼", email: "wb.niupanpan@mesg.corp.netease.com", department: "" },
  state: 1,
  taskCount: 1,
  column: 3,
  dueDate: '2020-10-10',
  keyResult: [],
  department: ['杭州研究院', '技术工程事业部', '项目管理与效能中心', '工程效能组'],
}, {
  bugCount: 0,
  dwManpower: {},
  id: 'Objective-71',
  issueKey: "Objective-71",
  parentIssueKey: 'Objective-3',
  issueRole: 1,
  issueType: 5,
  level: 3,
  name: "三级部门目标71",
  requirementCount: 5,
  responseUser: { id: 122, name: "牛盼盼", email: "wb.niupanpan@mesg.corp.netease.com", department: "" },
  state: 1,
  taskCount: 1,
  column: 3,
  dueDate: '2020-10-10',
  keyResult: [],
  department: ['杭州研究院', '技术工程事业部', '项目管理与效能中心', '工程效能组'],
}, {
  bugCount: 0,
  dwManpower: {},
  id: 'Objective-8',
  issueKey: "Objective-8",
  parentIssueKey: 'Objective-7',
  issueRole: 1,
  issueType: 5,
  level: 3,
  name: "四级部门目标8",
  requirementCount: 5,
  responseUser: { id: 122, name: "牛盼盼", email: "wb.niupanpan@mesg.corp.netease.com", department: "" },
  state: 1,
  taskCount: 1,
  column: 4,
  dueDate: '2020-10-10',
  keyResult: [{
    id: 1,
    name: '我是关键结果1'
  }, {
    id: 2,
    name: '我是关键结果2'
  }, {
    id: 3,
    name: '我是关键结果3'
  }],
  department: ['杭州研究院', '技术工程事业部', '项目管理与效能中心', '工程效能组'],
}, {
  bugCount: 0,
  dwManpower: {},
  id: 'Objective-81',
  issueKey: "Objective-81",
  parentIssueKey: 'Objective-7',
  issueRole: 1,
  issueType: 5,
  level: 3,
  name: "四级部门目标81",
  requirementCount: 5,
  responseUser: { id: 122, name: "牛盼盼", email: "wb.niupanpan@mesg.corp.netease.com", department: "" },
  state: 1,
  taskCount: 1,
  column: 4,
  dueDate: '2020-10-10',
  keyResult: [],
  department: ['杭州研究院', '技术工程事业部', '项目管理与效能中心', '工程效能组'],
}, {
  productId: '100',
  bugCount: 0,
  dwManpower: {},
  id: 'Objective-2',
  issueKey: "Objective-2",
  parentIssueKey: 'Objective-hidden0',
  issueRole: 1,
  issueType: 5,
  level: 3,
  name: "一级部门目标2",
  requirementCount: 5,
  responseUser: { id: 122, name: "牛盼盼", email: "wb.niupanpan@mesg.corp.netease.com", department: "" },
  state: 1,
  taskCount: 1,
  column: 1,
  dueDate: '2020-10-10',
  keyResult: [],
  department: ['杭州研究院', '技术工程事业部', '项目管理与效能中心', '工程效能组'],
}, {
  bugCount: 0,
  dwManpower: {},
  id: 'Objective-5',
  issueKey: "Objective-5",
  parentIssueKey: 'Objective-2',
  issueRole: 1,
  issueType: 5,
  level: 3,
  name: "二级部门目标5",
  requirementCount: 5,
  responseUser: { id: 122, name: "牛盼盼", email: "wb.niupanpan@mesg.corp.netease.com", department: "" },
  state: 1,
  taskCount: 1,
  column: 2,
  dueDate: '2020-10-10',
  keyResult: [],
  department: ['杭州研究院', '技术工程事业部', '项目管理与效能中心', '工程效能组'],
}, {
  bugCount: 0,
  dwManpower: {},
  id: 'Objective-6',
  issueKey: "Objective-6",
  parentIssueKey: 'Objective-2',
  issueRole: 1,
  issueType: 5,
  level: 3,
  name: "二级部门目标6",
  requirementCount: 5,
  responseUser: { id: 122, name: "牛盼盼", email: "wb.niupanpan@mesg.corp.netease.com", department: "" },
  state: 1,
  taskCount: 1,
  column: 2,
  dueDate: '2020-10-10',
  keyResult: [],
  department: ['杭州研究院', '技术工程事业部', '项目管理与效能中心', '工程效能组'],
}, {
  bugCount: 0,
  dwManpower: {},
  id: 'Objective-1111',
  issueKey: "Objective-1111",
  parentIssueKey: 'Objective-hidden0',
  issueRole: 1,
  issueType: 5,
  level: 3,
  name: "一级零散目标一",
  requirementCount: 5,
  responseUser: { id: 122, name: "牛盼盼", email: "wb.niupanpan@mesg.corp.netease.com", department: "" },
  state: 1,
  taskCount: 1,
  column: 1,
  dueDate: '2020-10-10',
  keyResult: [],
  department: ['杭州研究院', '技术工程事业部', '项目管理与效能中心', '工程效能组'],
}, {
  bugCount: 0,
  dwManpower: {},
  id: 'Objective-111',
  issueKey: "Objective-111",
  parentIssueKey: 'Objective-hidden1',
  issueRole: 1,
  issueType: 5,
  level: 3,
  name: "二级零散目标一",
  requirementCount: 5,
  responseUser: { id: 122, name: "牛盼盼", email: "wb.niupanpan@mesg.corp.netease.com", department: "" },
  state: 1,
  taskCount: 1,
  column: 2,
  dueDate: '2020-10-10',
  keyResult: [],
  department: ['杭州研究院', '技术工程事业部', '项目管理与效能中心', '工程效能组'],
}, {
  bugCount: 0,
  dwManpower: {},
  id: 'Objective-12',
  issueKey: "Objective-12",
  parentIssueKey: 'Objective-hidden2',
  issueRole: 1,
  issueType: 5,
  level: 3,
  name: "三级零散目标一",
  requirementCount: 5,
  responseUser: { id: 122, name: "牛盼盼", email: "wb.niupanpan@mesg.corp.netease.com", department: "" },
  state: 1,
  taskCount: 1,
  column: 3,
  dueDate: '2020-10-10',
  keyResult: [],
  department: ['杭州研究院', '技术工程事业部', '项目管理与效能中心', '工程效能组'],
}, {
  bugCount: 0,
  dwManpower: {},
  id: 'Objective-110',
  issueKey: "Objective-110",
  parentIssueKey: 'Objective-hidden3',
  issueRole: 1,
  issueType: 5,
  level: 3,
  name: "四级零散目标一",
  requirementCount: 5,
  responseUser: { id: 122, name: "牛盼盼", email: "wb.niupanpan@mesg.corp.netease.com", department: "" },
  state: 1,
  taskCount: 1,
  column: 4,
  dueDate: '2020-10-10',
  keyResult: [],
  department: ['杭州研究院', '技术工程事业部', '项目管理与效能中心', '工程效能组'],
}, {
  bugCount: 0,
  dwManpower: {},
  id: 'Objective-114',
  issueKey: "Objective-114",
  parentIssueKey: 'Objective-hidden3',
  issueRole: 1,
  issueType: 5,
  level: 3,
  name: "四级零散目标二",
  requirementCount: 5,
  responseUser: { id: 122, name: "牛盼盼", email: "wb.niupanpan@mesg.corp.netease.com", department: "" },
  state: 1,
  taskCount: 1,
  column: 4,
  dueDate: '2020-10-10',
  keyResult: [],
  department: ['杭州研究院', '技术工程事业部', '项目管理与效能中心', '工程效能组'],
}];

// export const displayData = {
//   bugCount: 0,
//   dwManpower: {},
//   id: 'Objective-hidden0',
//   issueKey: "Objective-hidden0",
//   issueRole: 1,
//   issueType: 5,
//   level: 3,
//   name: "大boss",
//   requirementCount: 5,
//   responseUser: { id: 122, name: "牛盼盼", email: "wb.niupanpan@mesg.corp.netease.com", department: "" },
//   state: 1,
//   taskCount: 1,
//   column: 1,
//   dueDate: '2020-10-10',
//   keyResult: [],
//   department: ['杭州研究院', '技术工程事业部', '项目管理与效能中心', '工程效能组'],
//   children: data,
// };

export const hiddenLevelData = [{
  bugCount: 0,
  dwManpower: {},
  id: 'Objective-hidden0',
  issueKey: "Objective-hidden0",
  issueRole: 1,
  issueType: 5,
  level: 3,
  name: "大boss",
  requirementCount: 5,
  responseUser: { id: 122, name: "牛盼盼", email: "wb.niupanpan@mesg.corp.netease.com", department: "" },
  state: 1,
  taskCount: 1,
  column: 0,
  dueDate: '2020-10-10',
  keyResult: [],
  department: ['杭州研究院', '技术工程事业部', '项目管理与效能中心', '工程效能组'],
  children: data,
}, {
  projectId: '100',
  id: 'Objective-hidden1',
  issueKey: "Objective-hidden1",
  parentIssueKey: 'Objective-hidden0',
  issueRole: 1,
  issueType: 5,
  level: 3,
  name: "hidden1",
  responseUser: { id: 122, name: "牛盼盼", email: "wb.niupanpan@mesg.corp.netease.com", department: "" },
  state: 1,
  column: 1,
  dueDate: '2020-10-10',
  keyResult: [],
  department: ['杭州研究院', '技术工程事业部', '项目管理与效能中心', '工程效能组'],
}, {
  bugCount: 0,
  dwManpower: {},
  id: 'Objective-hidden2',
  issueKey: "Objective-hidden2",
  parentIssueKey: 'Objective-hidden1',
  issueRole: 1,
  issueType: 5,
  level: 3,
  name: "hidden2",
  requirementCount: 5,
  responseUser: { id: 122, name: "牛盼盼", email: "wb.niupanpan@mesg.corp.netease.com", department: "" },
  state: 1,
  taskCount: 1,
  column: 2,
  dueDate: '2020-10-10',
  keyResult: [],
  department: ['杭州研究院', '技术工程事业部', '项目管理与效能中心', '工程效能组'],
}, {
  bugCount: 0,
  dwManpower: {},
  id: 'Objective-hidden3',
  issueKey: "Objective-hidden3",
  parentIssueKey: 'Objective-hidden2',
  issueRole: 1,
  issueType: 5,
  level: 3,
  name: "hidden3",
  requirementCount: 5,
  responseUser: { id: 122, name: "牛盼盼", email: "wb.niupanpan@mesg.corp.netease.com", department: "" },
  state: 1,
  taskCount: 1,
  column: 3,
  dueDate: '2020-10-10',
  keyResult: [],
  department: ['杭州研究院', '技术工程事业部', '项目管理与效能中心', '工程效能组'],
}, {
  bugCount: 0,
  dwManpower: {},
  id: 'Objective-hidden4',
  issueKey: "Objective-hidden4",
  parentIssueKey: 'Objective-hidden3',
  issueRole: 1,
  issueType: 5,
  level: 3,
  name: "hidden41",
  requirementCount: 5,
  responseUser: { id: 122, name: "牛盼盼", email: "wb.niupanpan@mesg.corp.netease.com", department: "" },
  state: 1,
  taskCount: 1,
  column: 4,
  dueDate: '2020-10-10',
  keyResult: [],
  department: ['杭州研究院', '技术工程事业部', '项目管理与效能中心', '工程效能组'],
}];

export const getData = () => {
  const newData = data;
  newData.forEach(item => {
    if (!item.parentIssueKey ||
      (item.parentIssueKey && !newData.some(it => it.issueKey === item.parentIssueKey))
    ) {
      item.parentIssueKey = `Objective-hidden${item.column - 1}`;
    }
  });
  return newData;
};

export const hejiData = [...getData(), ...hiddenLevelData];

